import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./custom-components/navbar";
import ModalHandler from "./handlers/RootModal";
import { Suspense } from "react";
import SessionWrapper from "./providers/SessionWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  modal,
  session,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
  session: any;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
          <Suspense fallback={<div>Loading...</div>}>
            <SessionWrapper session={session}>
              <Navbar/>
              {children}
              <ModalHandler modal={modal}/>
            </SessionWrapper>
          </Suspense>
        
      </body>
    </html>
  );
}
